### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by M5oul** [abeudin/ffsync_ynh#23]
@rigelk,
- You could move the app to [YunoHost-Apps organization](https://github.com/YunoHost-Apps/).
- Could you open issues on the repository.
- You could set yourself as maintainer on the manifest.
- set `"yunohost": ">> 2.5.4` as dependency on the manifest as [`git sumodules` was introduced on v.2.5.4](https://github.com/YunoHost/yunohost/releases/tag/debian%2F2.5.4).
- Line 51, I added `git clone https://github.com/mozilla-services/syncserver ../sources` as it seems `git submodule have an issue`. `../sources` folder is empty. See following point.
- I encounter an issue with v.1.6.2:
```bash
+ cd /opt/yunohost/ffsync
+ sudo make build
Warning: make: *** No rule to make target 'build'.  Stop.
+ '[' -z ']'
+ sudo swapoff
Warning: 
Warning: Usage:
Warning:  swapoff [options] [<spec>]
Warning: 
Warning: Options:
Warning:  -a, --all              disable all swaps from /proc/swaps
Warning:  -v, --verbose          verbose mode
Warning: 
Warning:  -h, --help     display this help and exit
Warning:  -V, --version  output version information and exit
Warning: 
+ sudo rm -f
Warning: The <spec> parameter:
Warning:  -L <label>             LABEL of device to be used
Warning:  -U <uuid>              UUID of device to be used
Warning:  LABEL=<label>          LABEL of device to be used
Warning:  UUID=<uuid>            UUID of device to be used
Warning:  <device>               name of device to be used
Warning:  <file>                 name of file to be used
Warning: 
Warning: For more details see swapoff(8).
+ sudo find /opt/yunohost/ffsync/ -type d -exec chmod 2755 '{}' ';'
+ sudo find /opt/yunohost/ffsync/ -type f -exec chmod g+r,o+r '{}' ';'
+ sudo chmod +x /etc/init.d/ffsync
+ sudo update-rc.d ffsync defaults
+ sudo service ffsync restart
Warning: Job for ffsync.service failed. See 'systemctl status ffsync.service' and 'journalctl -xn' for details.
+ sudo service ffsync restart
Warning: Job for ffsync.service failed. See 'systemctl status ffsync.service' and 'journalctl -xn' for details.
+ sudo service ffsync restart
Warning: Job for ffsync.service failed. See 'systemctl status ffsync.service' and 'journalctl -xn' for details.
+ sudo yunohost app ssowatconf
The SSOwat configuration has been generated
+ sudo service nginx restart
+ sudo yunohost service add ffsync -l /var/log/ffsync.log
The service 'ffsync' has been added
+ ynh_app_setting_set ffsync skipped_uris /
+ sudo yunohost app setting ffsync skipped_uris -v / --quiet
Success! The SSOwat configuration has been generated
Success! Installation complete
```

**Comment by rigelk** [comment]
The empty `sources` directory is due to the misuse of the `git submodules` command. I changed it in e42ac9f.

Of course we could get rid of the submodules if we need compatibility << 2.5.4, but we also lose track of the https://github.com/mozilla-services/syncserver upstream commit we support.

As for the transfer, I got the error "You don’t have the permission to create repositories on YunoHost-Apps".

**Comment by M5oul** [comment]
>The empty sources directory is due to the misuse of the git submodules command. I changed it in e42ac9f.

Ok, nice.

> Of course we could get rid of the submodules if we need compatibility << 2.5.4, but we also lose track of the https://github.com/mozilla-services/syncserver upstream commit we support.

Nope, `git submodule` is a good choice.

>As for the transfer, I got the error "You don’t have the permission to create repositories on YunoHost-Apps".

I invited you to YunoHost-apps organization. You could transfert ownership.
